import { FC } from "react";
import Link from 'next/link'
import { Abel } from "next/font/google";
import type { NextFont } from "next/dist/compiled/@next/font";
import { Metadata } from "next";

const abel: NextFont = Abel({
  subsets: ['latin'],
  weight: ['400']
})

const Footer: FC = () => {
  return (
    <footer className={`mb-2 ${abel.className} mt-6`}>
      <h6 className={'capitalize text-[0.5rem] md:text-xs'}>this blog was generated by VedK - younho kwak / this website repository : <Link href={'https://github.com/KwakYounHo/KSTUDIO'} target={'_blank'} className={'text-blue-400'}>github repository</Link></h6>
    </footer>
  )
}

export default Footer;