import { FC } from "react";
import Link from 'next/link'
import { Abel } from "next/font/google";
import type { NextFont } from "next/dist/compiled/@next/font";
import { Metadata } from "next";

const abel: NextFont = Abel({
  subsets: ['latin'],
  weight: ['400']
})

const Footer: FC = () => {
  return (
    <footer className={`mt-auto mb-2 ${abel.className}`}>
      <h6 className={'capitalize text-xs'}>this was blog generated by VedK - kwak youn ho git repository : <Link href={'https://github.com/KwakYounHo/KSTUDIO'} target={'_blank'} className={'text-blue-500'}>github repository</Link></h6>
    </footer>
  )
}

export default Footer;